export const countries = [
    { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫', flagUrl: '/assets/flags/af.png' },
    { code: 'AX', name: 'Åland Islands', dialCode: '+358', flag: '🇦🇽', flagUrl: '/assets/flags/ax.png' },
    { code: 'AL', name: 'Albania', dialCode: '+355', flag: '🇦🇱', flagUrl: '/assets/flags/al.png' },
    { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: '🇩🇿', flagUrl: '/assets/flags/dz.png' },
    { code: 'AS', name: 'American Samoa', dialCode: '+1684', flag: '🇦🇸', flagUrl: '/assets/flags/as.png' },
    { code: 'AD', name: 'Andorra', dialCode: '+376', flag: '🇦🇩', flagUrl: '/assets/flags/ad.png' },
    { code: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴', flagUrl: '/assets/flags/ao.png' },
    { code: 'AI', name: 'Anguilla', dialCode: '+1264', flag: '🇦🇮', flagUrl: '/assets/flags/ai.png' },
    { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1268', flag: '🇦🇬', flagUrl: '/assets/flags/ag.png' },
    { code: 'AR', name: 'Argentina', dialCode: '+54', flag: '🇦🇷', flagUrl: '/assets/flags/ar.png' },
    { code: 'AM', name: 'Armenia', dialCode: '+374', flag: '🇦🇲', flagUrl: '/assets/flags/am.png' },
    { code: 'AW', name: 'Aruba', dialCode: '+297', flag: '🇦🇼', flagUrl: '/assets/flags/aw.png' },
    { code: 'AU', name: 'Australia', dialCode: '+61', flag: '🇦🇺', flagUrl: '/assets/flags/au.png' },
    { code: 'AT', name: 'Austria', dialCode: '+43', flag: '🇦🇹', flagUrl: '/assets/flags/at.png' },
    { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿', flagUrl: '/assets/flags/az.png' },

    { code: 'BS', name: 'Bahamas', dialCode: '+1242', flag: '🇧🇸', flagUrl: '/assets/flags/bs.png' },
    { code: 'BH', name: 'Bahrain', dialCode: '+973', flag: '🇧🇭', flagUrl: '/assets/flags/bh.png' },
    { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', flagUrl: '/assets/flags/bd.png' },
    { code: 'BB', name: 'Barbados', dialCode: '+1246', flag: '🇧🇧', flagUrl: '/assets/flags/bb.png' },
    { code: 'BY', name: 'Belarus', dialCode: '+375', flag: '🇧🇾', flagUrl: '/assets/flags/by.png' },
    { code: 'BE', name: 'Belgium', dialCode: '+32', flag: '🇧🇪', flagUrl: '/assets/flags/be.png' },
    { code: 'BZ', name: 'Belize', dialCode: '+501', flag: '🇧🇿', flagUrl: '/assets/flags/bz.png' },
    { code: 'BJ', name: 'Benin', dialCode: '+229', flag: '🇧🇯', flagUrl: '/assets/flags/bj.png' },
    { code: 'BM', name: 'Bermuda', dialCode: '+1441', flag: '🇧🇲', flagUrl: '/assets/flags/bm.png' },
    { code: 'BT', name: 'Bhutan', dialCode: '+975', flag: '🇧🇹', flagUrl: '/assets/flags/bt.png' },
    { code: 'BO', name: 'Bolivia', dialCode: '+591', flag: '🇧🇴', flagUrl: '/assets/flags/bo.png' },
    { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦', flagUrl: '/assets/flags/ba.png' },
    { code: 'BW', name: 'Botswana', dialCode: '+267', flag: '🇧🇼', flagUrl: '/assets/flags/bw.png' },
    { code: 'BR', name: 'Brazil', dialCode: '+55', flag: '🇧🇷', flagUrl: '/assets/flags/br.png' },
    {
        code: 'IO',
        name: 'British Indian Ocean Territory',
        dialCode: '+246',
        flag: '🇮🇴',
        flagUrl: '/assets/flags/io.png',
    },
    { code: 'VG', name: 'British Virgin Islands', dialCode: '+1284', flag: '🇻🇬', flagUrl: '/assets/flags/vg.png' },
    { code: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳', flagUrl: '/assets/flags/bn.png' },
    { code: 'BG', name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬', flagUrl: '/assets/flags/bg.png' },
    { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫', flagUrl: '/assets/flags/bf.png' },
    { code: 'BI', name: 'Burundi', dialCode: '+257', flag: '🇧🇮', flagUrl: '/assets/flags/bi.png' },

    { code: 'KH', name: 'Cambodia', dialCode: '+855', flag: '🇰🇭', flagUrl: '/assets/flags/kh.png' },
    { code: 'CM', name: 'Cameroon', dialCode: '+237', flag: '🇨🇲', flagUrl: '/assets/flags/cm.png' },
    { code: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦', flagUrl: '/assets/flags/ca.png' },
    { code: 'CV', name: 'Cape Verde', dialCode: '+238', flag: '🇨🇻', flagUrl: '/assets/flags/cv.png' },
    { code: 'BQ', name: 'Caribbean Netherlands', dialCode: '+599', flag: '🇧🇶', flagUrl: '/assets/flags/bq.png' },
    { code: 'KY', name: 'Cayman Islands', dialCode: '+1345', flag: '🇰🇾', flagUrl: '/assets/flags/ky.png' },
    { code: 'CF', name: 'Central African Republic', dialCode: '+236', flag: '🇨🇫', flagUrl: '/assets/flags/cf.png' },
    { code: 'TD', name: 'Chad', dialCode: '+235', flag: '🇹🇩', flagUrl: '/assets/flags/td.png' },
    { code: 'CL', name: 'Chile', dialCode: '+56', flag: '🇨🇱', flagUrl: '/assets/flags/cl.png' },
    { code: 'CN', name: 'China', dialCode: '+86', flag: '🇨🇳', flagUrl: '/assets/flags/cn.png' },
    { code: 'CX', name: 'Christmas Island', dialCode: '+61', flag: '🇨🇽', flagUrl: '/assets/flags/cx.png' },
    { code: 'CC', name: 'Cocos (Keeling) Islands', dialCode: '+61', flag: '🇨🇨', flagUrl: '/assets/flags/cc.png' },
    { code: 'CO', name: 'Colombia', dialCode: '+57', flag: '🇨🇴', flagUrl: '/assets/flags/co.png' },
    { code: 'KM', name: 'Comoros', dialCode: '+269', flag: '🇰🇲', flagUrl: '/assets/flags/km.png' },
    { code: 'CG', name: 'Congo', dialCode: '+242', flag: '🇨🇬', flagUrl: '/assets/flags/cg.png' },
    {
        code: 'CD',
        name: 'Democratic Republic of the Congo',
        dialCode: '+243',
        flag: '🇨🇩',
        flagUrl: '/assets/flags/cd.png',
    },
    { code: 'CK', name: 'Cook Islands', dialCode: '+682', flag: '🇨🇰', flagUrl: '/assets/flags/ck.png' },
    { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷', flagUrl: '/assets/flags/cr.png' },
    { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225', flag: '🇨🇮', flagUrl: '/assets/flags/ci.png' },
    { code: 'HR', name: 'Croatia', dialCode: '+385', flag: '🇭🇷', flagUrl: '/assets/flags/hr.png' },
    { code: 'CU', name: 'Cuba', dialCode: '+53', flag: '🇨🇺', flagUrl: '/assets/flags/cu.png' },
    { code: 'CW', name: 'Curaçao', dialCode: '+599', flag: '🇨🇼', flagUrl: '/assets/flags/cw.png' },
    { code: 'CY', name: 'Cyprus', dialCode: '+357', flag: '🇨🇾', flagUrl: '/assets/flags/cy.png' },
    { code: 'CZ', name: 'Czech Republic', dialCode: '+420', flag: '🇨🇿', flagUrl: '/assets/flags/cz.png' },

    { code: 'DK', name: 'Denmark', dialCode: '+45', flag: '🇩🇰', flagUrl: '/assets/flags/dk.png' },
    { code: 'DJ', name: 'Djibouti', dialCode: '+253', flag: '🇩🇯', flagUrl: '/assets/flags/dj.png' },
    { code: 'DM', name: 'Dominica', dialCode: '+1767', flag: '🇩🇲', flagUrl: '/assets/flags/dm.png' },
    { code: 'DO', name: 'Dominican Republic', dialCode: '+1809', flag: '🇩🇴', flagUrl: '/assets/flags/do.png' },

    { code: 'EC', name: 'Ecuador', dialCode: '+593', flag: '🇪🇨', flagUrl: '/assets/flags/ec.png' },
    { code: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬', flagUrl: '/assets/flags/eg.png' },
    { code: 'SV', name: 'El Salvador', dialCode: '+503', flag: '🇸🇻', flagUrl: '/assets/flags/sv.png' },
    { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flag: '🇬🇶', flagUrl: '/assets/flags/gq.png' },
    { code: 'ER', name: 'Eritrea', dialCode: '+291', flag: '🇪🇷', flagUrl: '/assets/flags/er.png' },
    { code: 'EE', name: 'Estonia', dialCode: '+372', flag: '🇪🇪', flagUrl: '/assets/flags/ee.png' },
    { code: 'SZ', name: 'Eswatini', dialCode: '+268', flag: '🇸🇿', flagUrl: '/assets/flags/sz.png' },
    { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹', flagUrl: '/assets/flags/et.png' },

    { code: 'FK', name: 'Falkland Islands', dialCode: '+500', flag: '🇫🇰', flagUrl: '/assets/flags/fk.png' },
    { code: 'FO', name: 'Faroe Islands', dialCode: '+298', flag: '🇫🇴', flagUrl: '/assets/flags/fo.png' },
    { code: 'FJ', name: 'Fiji', dialCode: '+679', flag: '🇫🇯', flagUrl: '/assets/flags/fj.png' },
    { code: 'FI', name: 'Finland', dialCode: '+358', flag: '🇫🇮', flagUrl: '/assets/flags/fi.png' },
    { code: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷', flagUrl: '/assets/flags/fr.png' },
    { code: 'GF', name: 'French Guiana', dialCode: '+594', flag: '🇬🇫', flagUrl: '/assets/flags/gf.png' },
    { code: 'PF', name: 'French Polynesia', dialCode: '+689', flag: '🇵🇫', flagUrl: '/assets/flags/pf.png' },

    { code: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦', flagUrl: '/assets/flags/ga.png' },
    { code: 'GM', name: 'Gambia', dialCode: '+220', flag: '🇬🇲', flagUrl: '/assets/flags/gm.png' },
    { code: 'GE', name: 'Georgia', dialCode: '+995', flag: '🇬🇪', flagUrl: '/assets/flags/ge.png' },
    { code: 'DE', name: 'Germany', dialCode: '+49', flag: '🇩🇪', flagUrl: '/assets/flags/de.png' },
    { code: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭', flagUrl: '/assets/flags/gh.png' },
    { code: 'GI', name: 'Gibraltar', dialCode: '+350', flag: '🇬🇮', flagUrl: '/assets/flags/gi.png' },
    { code: 'GR', name: 'Greece', dialCode: '+30', flag: '🇬🇷', flagUrl: '/assets/flags/gr.png' },
    { code: 'GL', name: 'Greenland', dialCode: '+299', flag: '🇬🇱', flagUrl: '/assets/flags/gl.png' },
    { code: 'GD', name: 'Grenada', dialCode: '+1473', flag: '🇬🇩', flagUrl: '/assets/flags/gd.png' },
    { code: 'GP', name: 'Guadeloupe', dialCode: '+590', flag: '🇬🇵', flagUrl: '/assets/flags/gp.png' },
    { code: 'GU', name: 'Guam', dialCode: '+1671', flag: '🇬🇺', flagUrl: '/assets/flags/gu.png' },
    { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: '🇬🇹', flagUrl: '/assets/flags/gt.png' },
    { code: 'GG', name: 'Guernsey', dialCode: '+44', flag: '🇬🇬', flagUrl: '/assets/flags/gg.png' },
    { code: 'GN', name: 'Guinea', dialCode: '+224', flag: '🇬🇳', flagUrl: '/assets/flags/gn.png' },
    { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flag: '🇬🇼', flagUrl: '/assets/flags/gw.png' },
    { code: 'GY', name: 'Guyana', dialCode: '+592', flag: '🇬🇾', flagUrl: '/assets/flags/gy.png' },

    { code: 'HT', name: 'Haiti', dialCode: '+509', flag: '🇭🇹', flagUrl: '/assets/flags/ht.png' },
    { code: 'HN', name: 'Honduras', dialCode: '+504', flag: '🇭🇳', flagUrl: '/assets/flags/hn.png' },
    { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰', flagUrl: '/assets/flags/hk.png' },
    { code: 'HU', name: 'Hungary', dialCode: '+36', flag: '🇭🇺', flagUrl: '/assets/flags/hu.png' },

    { code: 'IS', name: 'Iceland', dialCode: '+354', flag: '🇮🇸', flagUrl: '/assets/flags/is.png' },
    { code: 'IN', name: 'India', dialCode: '+91', flag: '🇮🇳', flagUrl: '/assets/flags/in.png' },
    { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩', flagUrl: '/assets/flags/id.png' },
    { code: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷', flagUrl: '/assets/flags/ir.png' },
    { code: 'IQ', name: 'Iraq', dialCode: '+964', flag: '🇮🇶', flagUrl: '/assets/flags/iq.png' },
    { code: 'IE', name: 'Ireland', dialCode: '+353', flag: '🇮🇪', flagUrl: '/assets/flags/ie.png' },
    { code: 'IM', name: 'Isle of Man', dialCode: '+44', flag: '🇮🇲', flagUrl: '/assets/flags/im.png' },
    { code: 'IL', name: 'Israel', dialCode: '+972', flag: '🇮🇱', flagUrl: '/assets/flags/il.png' },
    { code: 'IT', name: 'Italy', dialCode: '+39', flag: '🇮🇹', flagUrl: '/assets/flags/it.png' },

    { code: 'JM', name: 'Jamaica', dialCode: '+1876', flag: '🇯🇲', flagUrl: '/assets/flags/jm.png' },
    { code: 'JP', name: 'Japan', dialCode: '+81', flag: '🇯🇵', flagUrl: '/assets/flags/jp.png' },
    { code: 'JE', name: 'Jersey', dialCode: '+44', flag: '🇯🇪', flagUrl: '/assets/flags/je.png' },
    { code: 'JO', name: 'Jordan', dialCode: '+962', flag: '🇯🇴', flagUrl: '/assets/flags/jo.png' },

    { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿', flagUrl: '/assets/flags/kz.png' },
    { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', flagUrl: '/assets/flags/ke.png' },
    { code: 'KI', name: 'Kiribati', dialCode: '+686', flag: '🇰🇮', flagUrl: '/assets/flags/ki.png' },
    { code: 'KP', name: 'North Korea', dialCode: '+850', flag: '🇰🇵', flagUrl: '/assets/flags/kp.png' },
    { code: 'KR', name: 'South Korea', dialCode: '+82', flag: '🇰🇷', flagUrl: '/assets/flags/kr.png' },
    { code: 'KW', name: 'Kuwait', dialCode: '+965', flag: '🇰🇼', flagUrl: '/assets/flags/kw.png' },
    { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', flag: '🇰🇬', flagUrl: '/assets/flags/kg.png' },

    { code: 'LA', name: 'Laos', dialCode: '+856', flag: '🇱🇦', flagUrl: '/assets/flags/la.png' },
    { code: 'LV', name: 'Latvia', dialCode: '+371', flag: '🇱🇻', flagUrl: '/assets/flags/lv.png' },
    { code: 'LB', name: 'Lebanon', dialCode: '+961', flag: '🇱🇧', flagUrl: '/assets/flags/lb.png' },
    { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: '🇱🇸', flagUrl: '/assets/flags/ls.png' },
    { code: 'LR', name: 'Liberia', dialCode: '+231', flag: '🇱🇷', flagUrl: '/assets/flags/lr.png' },
    { code: 'LY', name: 'Libya', dialCode: '+218', flag: '🇱🇾', flagUrl: '/assets/flags/ly.png' },
    { code: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮', flagUrl: '/assets/flags/li.png' },
    { code: 'LT', name: 'Lithuania', dialCode: '+370', flag: '🇱🇹', flagUrl: '/assets/flags/lt.png' },
    { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺', flagUrl: '/assets/flags/lu.png' },

    { code: 'MO', name: 'Macao', dialCode: '+853', flag: '🇲🇴', flagUrl: '/assets/flags/mo.png' },
    { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: '🇲🇬', flagUrl: '/assets/flags/mg.png' },
    { code: 'MW', name: 'Malawi', dialCode: '+265', flag: '🇲🇼', flagUrl: '/assets/flags/mw.png' },
    { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾', flagUrl: '/assets/flags/my.png' },
    { code: 'MV', name: 'Maldives', dialCode: '+960', flag: '🇲🇻', flagUrl: '/assets/flags/mv.png' },
    { code: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱', flagUrl: '/assets/flags/ml.png' },
    { code: 'MT', name: 'Malta', dialCode: '+356', flag: '🇲🇹', flagUrl: '/assets/flags/mt.png' },
    { code: 'MH', name: 'Marshall Islands', dialCode: '+692', flag: '🇲🇭', flagUrl: '/assets/flags/mh.png' },
    { code: 'MQ', name: 'Martinique', dialCode: '+596', flag: '🇲🇶', flagUrl: '/assets/flags/mq.png' },
    { code: 'MR', name: 'Mauritania', dialCode: '+222', flag: '🇲🇷', flagUrl: '/assets/flags/mr.png' },
    { code: 'MU', name: 'Mauritius', dialCode: '+230', flag: '🇲🇺', flagUrl: '/assets/flags/mu.png' },
    { code: 'YT', name: 'Mayotte', dialCode: '+262', flag: '🇾🇹', flagUrl: '/assets/flags/fr.png' },
    { code: 'MX', name: 'Mexico', dialCode: '+52', flag: '🇲🇽', flagUrl: '/assets/flags/mx.png' },
    { code: 'FM', name: 'Micronesia', dialCode: '+691', flag: '🇫🇲', flagUrl: '/assets/flags/fm.png' },
    { code: 'MD', name: 'Moldova', dialCode: '+373', flag: '🇲🇩', flagUrl: '/assets/flags/md.png' },
    { code: 'MC', name: 'Monaco', dialCode: '+377', flag: '🇲🇨', flagUrl: '/assets/flags/mc.png' },
    { code: 'MN', name: 'Mongolia', dialCode: '+976', flag: '🇲🇳', flagUrl: '/assets/flags/mn.png' },
    { code: 'ME', name: 'Montenegro', dialCode: '+382', flag: '🇲🇪', flagUrl: '/assets/flags/me.png' },
    { code: 'MS', name: 'Montserrat', dialCode: '+1664', flag: '🇲🇸', flagUrl: '/assets/flags/ms.png' },
    { code: 'MA', name: 'Morocco', dialCode: '+212', flag: '🇲🇦', flagUrl: '/assets/flags/ma.png' },
    { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: '🇲🇿', flagUrl: '/assets/flags/mz.png' },
    { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲', flagUrl: '/assets/flags/mm.png' },

    { code: 'NA', name: 'Namibia', dialCode: '+264', flag: '🇳🇦', flagUrl: '/assets/flags/na.png' },
    { code: 'NR', name: 'Nauru', dialCode: '+674', flag: '🇳🇷', flagUrl: '/assets/flags/nr.png' },
    { code: 'NP', name: 'Nepal', dialCode: '+977', flag: '🇳🇵', flagUrl: '/assets/flags/np.png' },
    { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: '🇳🇱', flagUrl: '/assets/flags/nl.png' },
    { code: 'NC', name: 'New Caledonia', dialCode: '+687', flag: '🇳🇨', flagUrl: '/assets/flags/nc.png' },
    { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: '🇳🇿', flagUrl: '/assets/flags/nz.png' },
    { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: '🇳🇮', flagUrl: '/assets/flags/ni.png' },
    { code: 'NE', name: 'Niger', dialCode: '+227', flag: '🇳🇪', flagUrl: '/assets/flags/ne.png' },
    { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬', flagUrl: '/assets/flags/ng.png' },
    { code: 'NU', name: 'Niue', dialCode: '+683', flag: '🇳🇺', flagUrl: '/assets/flags/nu.png' },
    { code: 'NF', name: 'Norfolk Island', dialCode: '+672', flag: '🇳🇫', flagUrl: '/assets/flags/nf.png' },
    { code: 'MK', name: 'North Macedonia', dialCode: '+389', flag: '🇲🇰', flagUrl: '/assets/flags/mk.png' },
    { code: 'MP', name: 'Northern Mariana Islands', dialCode: '+1670', flag: '🇲🇵', flagUrl: '/assets/flags/mp.png' },
    { code: 'NO', name: 'Norway', dialCode: '+47', flag: '🇳🇴', flagUrl: '/assets/flags/no.png' },

    { code: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲', flagUrl: '/assets/flags/om.png' },

    { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', flagUrl: '/assets/flags/pk.png' },
    { code: 'PW', name: 'Palau', dialCode: '+680', flag: '🇵🇼', flagUrl: '/assets/flags/pw.png' },
    { code: 'PS', name: 'Palestine', dialCode: '+970', flag: '🇵🇸', flagUrl: '/assets/flags/ps.png' },
    { code: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦', flagUrl: '/assets/flags/pa.png' },
    { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬', flagUrl: '/assets/flags/pg.png' },
    { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾', flagUrl: '/assets/flags/py.png' },
    { code: 'PE', name: 'Peru', dialCode: '+51', flag: '🇵🇪', flagUrl: '/assets/flags/pe.png' },
    { code: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭', flagUrl: '/assets/flags/ph.png' },
    { code: 'PN', name: 'Pitcairn Islands', dialCode: '+64', flag: '🇵🇳', flagUrl: '/assets/flags/pn.png' },
    { code: 'PL', name: 'Poland', dialCode: '+48', flag: '🇵🇱', flagUrl: '/assets/flags/pl.png' },
    { code: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹', flagUrl: '/assets/flags/pt.png' },
    { code: 'PR', name: 'Puerto Rico', dialCode: '+1787', flag: '🇵🇷', flagUrl: '/assets/flags/pr.png' },

    { code: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦', flagUrl: '/assets/flags/qa.png' },

    { code: 'RE', name: 'Réunion', dialCode: '+262', flag: '🇷🇪', flagUrl: '/assets/flags/re.png' },
    { code: 'RO', name: 'Romania', dialCode: '+40', flag: '🇷🇴', flagUrl: '/assets/flags/ro.png' },
    { code: 'RU', name: 'Russia', dialCode: '+7', flag: '🇷🇺', flagUrl: '/assets/flags/ru.png' },
    { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: '🇷🇼', flagUrl: '/assets/flags/rw.png' },

    { code: 'BL', name: 'Saint Barthélemy', dialCode: '+590', flag: '🇧🇱', flagUrl: '/assets/flags/fr.png' },
    { code: 'SH', name: 'Saint Helena', dialCode: '+290', flag: '🇸🇭', flagUrl: '/assets/flags/sh.png' },
    { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1869', flag: '🇰🇳', flagUrl: '/assets/flags/kn.png' },
    { code: 'LC', name: 'Saint Lucia', dialCode: '+1758', flag: '🇱🇨', flagUrl: '/assets/flags/lc.png' },
    { code: 'MF', name: 'Saint Martin', dialCode: '+590', flag: '🇲🇫', flagUrl: '/assets/flags/mf.png' },
    { code: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '+508', flag: '🇵🇲', flagUrl: '/assets/flags/fr.png' },
    {
        code: 'VC',
        name: 'Saint Vincent and the Grenadines',
        dialCode: '+1784',
        flag: '🇻🇨',
        flagUrl: '/assets/flags/vc.png',
    },
    { code: 'WS', name: 'Samoa', dialCode: '+685', flag: '🇼🇸', flagUrl: '/assets/flags/ws.png' },
    { code: 'SM', name: 'San Marino', dialCode: '+378', flag: '🇸🇲', flagUrl: '/assets/flags/sm.png' },
    { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', flag: '🇸🇹', flagUrl: '/assets/flags/st.png' },
    { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦', flagUrl: '/assets/flags/sa.png' },
    { code: 'SN', name: 'Senegal', dialCode: '+221', flag: '🇸🇳', flagUrl: '/assets/flags/sn.png' },
    { code: 'RS', name: 'Serbia', dialCode: '+381', flag: '🇷🇸', flagUrl: '/assets/flags/rs.png' },
    { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: '🇸🇨', flagUrl: '/assets/flags/sc.png' },
    { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱', flagUrl: '/assets/flags/sl.png' },
    { code: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬', flagUrl: '/assets/flags/sg.png' },
    { code: 'SX', name: 'Sint Maarten', dialCode: '+1721', flag: '🇸🇽', flagUrl: '/assets/flags/sx.png' },
    { code: 'SK', name: 'Slovakia', dialCode: '+421', flag: '🇸🇰', flagUrl: '/assets/flags/sk.png' },
    { code: 'SI', name: 'Slovenia', dialCode: '+386', flag: '🇸🇮', flagUrl: '/assets/flags/si.png' },
    { code: 'SB', name: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧', flagUrl: '/assets/flags/sb.png' },
    { code: 'SO', name: 'Somalia', dialCode: '+252', flag: '🇸🇴', flagUrl: '/assets/flags/so.png' },
    { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: '🇿🇦', flagUrl: '/assets/flags/za.png' },
    { code: 'SS', name: 'South Sudan', dialCode: '+211', flag: '🇸🇸', flagUrl: '/assets/flags/ss.png' },
    { code: 'ES', name: 'Spain', dialCode: '+34', flag: '🇪🇸', flagUrl: '/assets/flags/es.png' },
    { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰', flagUrl: '/assets/flags/lk.png' },
    { code: 'SD', name: 'Sudan', dialCode: '+249', flag: '🇸🇩', flagUrl: '/assets/flags/sd.png' },
    { code: 'SR', name: 'Suriname', dialCode: '+597', flag: '🇸🇷', flagUrl: '/assets/flags/sr.png' },
    { code: 'SJ', name: 'Svalbard and Jan Mayen', dialCode: '+47', flag: '🇸🇯', flagUrl: '/assets/flags/sj.png' },
    { code: 'SE', name: 'Sweden', dialCode: '+46', flag: '🇸🇪', flagUrl: '/assets/flags/se.png' },
    { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: '🇨🇭', flagUrl: '/assets/flags/ch.png' },
    { code: 'SY', name: 'Syria', dialCode: '+963', flag: '🇸🇾', flagUrl: '/assets/flags/sy.png' },

    { code: 'TW', name: 'Taiwan', dialCode: '+886', flag: '🇹🇼', flagUrl: '/assets/flags/tw.png' },
    { code: 'TJ', name: 'Tajikistan', dialCode: '+992', flag: '🇹🇯', flagUrl: '/assets/flags/tj.png' },
    { code: 'TZ', name: 'Tanzania', dialCode: '+255', flag: '🇹🇿', flagUrl: '/assets/flags/tz.png' },
    { code: 'TH', name: 'Thailand', dialCode: '+66', flag: '🇹🇭', flagUrl: '/assets/flags/th.png' },
    { code: 'TL', name: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱', flagUrl: '/assets/flags/tl.png' },
    { code: 'TG', name: 'Togo', dialCode: '+228', flag: '🇹🇬', flagUrl: '/assets/flags/tg.png' },
    { code: 'TK', name: 'Tokelau', dialCode: '+690', flag: '🇹🇰', flagUrl: '/assets/flags/tk.png' },
    { code: 'TO', name: 'Tonga', dialCode: '+676', flag: '🇹🇴', flagUrl: '/assets/flags/to.png' },
    { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868', flag: '🇹🇹', flagUrl: '/assets/flags/tt.png' },
    { code: 'TN', name: 'Tunisia', dialCode: '+216', flag: '🇹🇳', flagUrl: '/assets/flags/tn.png' },
    { code: 'TR', name: 'Turkey', dialCode: '+90', flag: '🇹🇷', flagUrl: '/assets/flags/tr.png' },
    { code: 'TM', name: 'Turkmenistan', dialCode: '+993', flag: '🇹🇲', flagUrl: '/assets/flags/tm.png' },
    { code: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1649', flag: '🇹🇨', flagUrl: '/assets/flags/tc.png' },
    { code: 'TV', name: 'Tuvalu', dialCode: '+688', flag: '🇹🇻', flagUrl: '/assets/flags/tv.png' },

    { code: 'UG', name: 'Uganda', dialCode: '+256', flag: '🇺🇬', flagUrl: '/assets/flags/ug.png' },
    { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: '🇺🇦', flagUrl: '/assets/flags/ua.png' },
    { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪', flagUrl: '/assets/flags/ae.png' },
    { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧', flagUrl: '/assets/flags/gb.png' },
    { code: 'US', name: 'United States', dialCode: '+1', flag: '🇺🇸', flagUrl: '/assets/flags/us.png' },
    { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾', flagUrl: '/assets/flags/uy.png' },
    { code: 'VI', name: 'US Virgin Islands', dialCode: '+1340', flag: '🇻🇮', flagUrl: '/assets/flags/vi.png' },
    { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿', flagUrl: '/assets/flags/uz.png' },

    { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺', flagUrl: '/assets/flags/vu.png' },
    { code: 'VA', name: 'Vatican City', dialCode: '+39', flag: '🇻🇦', flagUrl: '/assets/flags/va.png' },
    { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪', flagUrl: '/assets/flags/ve.png' },
    { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', flagUrl: '/assets/flags/vn.png' },

    { code: 'WF', name: 'Wallis and Futuna', dialCode: '+681', flag: '🇼🇫', flagUrl: '/assets/flags/fr.png' },

    { code: 'YE', name: 'Yemen', dialCode: '+967', flag: '🇾🇪', flagUrl: '/assets/flags/ye.png' },

    { code: 'ZM', name: 'Zambia', dialCode: '+260', flag: '🇿🇲', flagUrl: '/assets/flags/zm.png' },
    { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', flagUrl: '/assets/flags/zw.png' },
];

export const getCountryByCode = (code) => {
    if (!code) return undefined;

    return countries.find((country) => country.code === code.trim().toUpperCase());
};

export const getCountriesByDialCode = (dialCode) => {
    if (!dialCode) return [];

    const normalizedDialCode = String(dialCode).startsWith('+') ? String(dialCode) : `+${dialCode}`;

    return countries.filter((country) => country.dialCode === normalizedDialCode);
};

export const getCountryByDialCode = (dialCode) => {
    return getCountriesByDialCode(dialCode)[0];
};

export const getCountryByName = (name) => {
    if (!name) return undefined;

    const normalizedName = name.trim().toLowerCase();

    return countries.find((country) => country.name.toLowerCase() === normalizedName);
};
